### ISSUE TITLE
建议增加fofa的语法搜索

### ISSUE THREAD

**Issue by kepler404** [EdgeSecurityTeam/EHole#1]
例如--fofa domain="baidu.com"，然后直接开始跑，
--fofa app="JBoss",类似这种的
--fofa app="JBoss" && country="BR"
支持大佬

**Comment by ShiHuang-ESec** [comment]
nice

**Comment by lapalipi** [comment]
➜  Ehole2.0-darwin ./Ehole_v2_darwin -f 222.66.109.0/24

     ______    __         ______
    / ____/___/ /___ ____/_  __/__  ____ _____ ___
   / __/ / __  / __ `/ _ \/ / / _ \/ __ `/ __ `__ \
  / /___/ /_/ / /_/ /  __/ / /  __/ /_/ / / / / / /
 /_____/\__,_/\__, /\___/_/  \___/\__,_/_/ /_/ /_/
			 /____/ https://forum.ywhack.com  By:shihuang

请耐心等待fofa搜索......

重点资产：
fofa共收集：0条，已识别资产：0条


运行时间：924.80708ms

接口挂了？？

**Comment by r0eXpeR** [comment]
新版已支持。
