### ISSUE TITLE
2.0的效果比3.0好多了

### ISSUE THREAD

**Issue by safebaseline** [EdgeSecurityTeam/EHole#19]
3.0感觉有bug
2.0截图
![image](https://user-images.githubusercontent.com/38883009/138215472-66018045-775c-46de-84f4-48b2810e0209.png)
3.0截图
![image](https://user-images.githubusercontent.com/38883009/138215517-0fca2313-b2f5-4cfe-9fba-1f9a9c3421ee.png)
3.0版本啥都没有，连过程都没有

**Comment by wqe0520** [comment]
刚去下了也是跟楼主一样的情况。

**Comment by 0x6869** [comment]
确实收集不到

**Comment by r0eXpeR** [comment]
最新版本需要自己重新编译。
