### ISSUE TITLE
windows版识别url文件时侯有个小问题

### ISSUE THREAD

**Issue by InkNull** [EdgeSecurityTeam/EHole#2]
大佬，windows版识别url文件时，url文档里第一行需要空出来才能识别

**Comment by ShiHuang-ESec** [comment]
我这边测试好几台机器都没有发现你这个问题，玄学了

**Comment by InkNull** [comment]
![image](https://user-images.githubusercontent.com/42135405/106983253-90668c00-67a0-11eb-8076-7a3bb87ee9c2.png)
大概就是这个样子的，这是另台电脑的情况。

**Comment by ShiHuang-ESec** [comment]
![image](https://user-images.githubusercontent.com/50050036/106996070-28716f00-67bb-11eb-9af0-7cbcdc19b359.png)
建议在文本末尾加上一个空行，因为是按行读取，所以只有一行的话会丢失结果

**Comment by ShiHuang-ESec** [comment]
这个问题新版本已经解决，感谢你提出的建议！！
