### ISSUE TITLE
fofa 识别有问题，一下就结束了。已经配置密钥

### ISSUE THREAD

**Issue by simlelcf** [EdgeSecurityTeam/EHole#3]
![image](https://user-images.githubusercontent.com/18651522/110882586-28661100-831d-11eb-87fa-c68aad7a69af.png)
![image](https://user-images.githubusercontent.com/18651522/110882636-3fa4fe80-831d-11eb-90c9-fb2529370901.png)

**Comment by lapalipi** [comment]
我是可以的，更新一下fofa接口吧，看看是不是fofa接口的锅。
PS：就是高亮好像没得了。

**Comment by simlelcf** [comment]
fofa 接口没问题，我是普通会员
![Uploading image.png…]()

**Comment by simlelcf** [comment]
![image](https://user-images.githubusercontent.com/18651522/110892986-0fb32680-8330-11eb-876e-153436fe6aad.png)

**Comment by simlelcf** [comment]
解决了必须要高级会员才可以IP查询，但有个问题，查询单IP，只要一条记录的时候显示查到，但没有结果。
![image](https://user-images.githubusercontent.com/18651522/110903074-d4b9ee80-8341-11eb-8535-9f37637823c2.png)

**Comment by ShiHuang-ESec** [comment]
fofa查出来的不一定能访问
