### ISSUE TITLE
把so改为info编译后缺少配置文件

### ISSUE THREAD

**Issue by VVeakee** [EdgeSecurityTeam/EHole#33]
![图片](https://user-images.githubusercontent.com/85714114/160252255-ff92a4c5-bf8d-4184-8257-5b3ad50df655.png)

应该是没有自动生成,我又不知道配置文件的格式怎么写...

**Comment by ShiHuang-ESec** [comment]
Email=xxxxxxxxx@admin.com
Fofa_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Fofa_timeout=10
