### ISSUE TITLE
新版本无法正常使用

### ISSUE THREAD

**Issue by ruisika** [EdgeSecurityTeam/EHole#58]
![image](https://github.com/EdgeSecurityTeam/EHole/assets/87137234/7ccc7336-b53b-4b14-88d6-51a3e74018b6)
PS D:\CY\scan\ehole> .\EHole_windows_amd64.exe -l .\1.txt
Error: unknown shorthand flag: 'l' in -l
Usage:
  ehole [command]

Available Commands:
  finger      ehole的指纹识别模块
  fofaext     ehole的fofa提取模块
  help        Help about any command

Flags:
      --config string   config file (default is $HOME/.ehole.yaml)
  -h, --help            help for ehole
  -t, --toggle          Help message for toggle

Use "ehole [command] --help" for more information about a command.

Error: unknown shorthand flag: 'l' in -l

**Comment by r0eXpeR** [comment]
EHole.exe finger -l .\1.txt
