### ISSUE TITLE
3.1报错

### ISSUE THREAD

**Issue by LOONG001** [EdgeSecurityTeam/EHole#59]
![image](https://github.com/EdgeSecurityTeam/EHole/assets/34571314/9721bd73-b0c5-44c9-8a08-f8792b4047b9)
![image](https://github.com/EdgeSecurityTeam/EHole/assets/34571314/a3425fdf-1394-4cc5-964b-c94740f0262d)
![image](https://github.com/EdgeSecurityTeam/EHole/assets/34571314/36b001f7-de9f-4bf8-a1c1-295ae1644ac5)
![image](https://github.com/EdgeSecurityTeam/EHole/assets/34571314/a63236e4-5cc5-4615-b1fb-9d716802e78e)

**Comment by r0eXpeR** [comment]
这个提示是你没有把指纹文件 finger.json 放进去吧。 都有提示的。
