### ISSUE TITLE
总是出现[error] fingerprint file error!!!的报错

### ISSUE THREAD

**Issue by TheBeastofwar** [EdgeSecurityTeam/EHole#65]
go run main.go finger -l url.txt

     ______    __         ______                 
    / ____/___/ /___ ____/_  __/__  ____ _____ ___ 
   / __/ / __  / __ `/ _ \/ / / _ \/ __ `/ __ `__ \
  / /___/ /_/ / /_/ /  __/ / /  __/ /_/ / / / / / /
 /_____/\__,_/\__, /\___/_/  \___/\__,_/_/ /_/ /_/ 
			 /____/ https://forum.ywhack.com  By:shihuang

[error] fingerprint file error!!!
exit status 1

**Comment by r0eXpeR** [comment]
更新了附件，请下载带有配置文件的对应版本。
