### ISSUE TITLE
Error: unknown shorthand flag: 'l' in -l   ？？？

### ISSUE THREAD

**Issue by helloworldbugs** [EdgeSecurityTeam/EHole#68]
什么问题？不能识别-l命令？
![image](https://github.com/EdgeSecurityTeam/EHole/assets/84578970/67fb491c-08dd-469b-b107-e0c0fb7a1d25)

**Comment by helloworldbugs** [comment]
我用的最新版3.1。是命令方式改了？有没有更新使用手册？

**Comment by yuzezheng416** [comment]
EHole_windows_amd64.exe finger -l  试试？
