### ISSUE TITLE
关于只能识别一个cms的问题

### ISSUE THREAD

**Issue by tgllsy** [EdgeSecurityTeam/EHole#7]
我在自己添加指纹特征的时候发现一个问题，目标只能匹配一个cms规则，当出现多个规则命中，只能显示一个，导致了我自己写的规则无效。但是当原先的cms规则为None时。添加的规则就能正常显示。
希望能修复一下，出现多个规则时候能同时展示。
![gi](https://user-images.githubusercontent.com/19581396/114301215-74f86400-9af6-11eb-85e1-324653120f18.png)

**Comment by ShiHuang-ESec** [comment]
感觉很多人想用这个功能

**Comment by r0eXpeR** [comment]
新版已支持。
