### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by EASY233** [EdgeSecurityTeam/EHole#8]
首先非常感谢大佬开发的优秀程序，这里提几个建议，都是我使用过程中发现的问题
 - 1.输出保存支持实在太少了，只支持json输出。希望能够提供html或者csv的保存方式。
 - 2.输出保存里面竟然没有把重点资产给分开来？？
 -  3.有意向开源吗，想要学习一下，或根据个人使用修改一下源码。
希望大佬能够采纳~~

**Comment by ShiHuang-ESec** [comment]
感谢你提出的意见，不久会支持输出xlsx，输出json格式本意是让棱洞能嵌入到别的程序或者框架里，所以没有对资产进行过滤，关于开源的问题此处有解答：https://github.com/ShiHuang-ESec/EHole/issues/2

**Comment by cqliukee** [comment]
ShiHuang-ESec/EHole#2
测试可以用。

EdgeSecurityTeam：2，3版本扫描后不出结果。在WIn10，Macos

**Comment by cqliukee** [comment]
sudo ./Ehole-darwin  -v

     ______    __         ______
    / ____/___/ /___ ____/_  __/__  ____ _____ ___
   / __/ / __  / __ `/ _ \/ / / _ \/ __ `/ __ `__ \
  / /___/ /_/ / /_/ /  __/ / /  __/ /_/ / / / / / /
 /_____/\__,_/\__, /\___/_/  \___/\__,_/_/ /_/ /_/
			 /____/ https://forum.ywhack.com  By:shihuang

flag provided but not defined: -v
Ehole version: 3.0
Usage: Ehole [-f|-l] [parameter]

udo ./Ehole-darwin -f 60.8.125.1/24
Password:

     ______    __         ______
    / ____/___/ /___ ____/_  __/__  ____ _____ ___
   / __/ / __  / __ `/ _ \/ / / _ \/ __ `/ __ `__ \
  / /___/ /_/ / /_/ /  __/ / /  __/ /_/ / / / / / /
 /_____/\__,_/\__, /\___/_/  \___/\__,_/_/ /_/ /_/
			 /____/ https://forum.ywhack.com  By:shihuang

请耐心等待fofa搜索......

重点资产：
fofa共收集：0条，已识别资产：0条


运行时间：10.889387446s%

Ehole_win_v0.0.2>Ehole_v0.0.2.exe -f 60.8.125.1/24

     ______    __         ______
    / ____/___/ /___ ____/_  __/__  ____ _____ ___
   / __/ / __  / __ `/ _ \/ / / _ \/ __ `/ __ `__ \
  / /___/ /_/ / /_/ /  __/ / /  __/ /_/ / / / / / /
 /_____/\__,_/\__, /\___/_/  \___/\__,_/_/ /_/ /_/
                         /____/ https://forum.ywhack.com  By:shihuang

请耐心等待fofa搜索......
[ http://60.8.125.74:8093 | nginx | 200 | 3765 | None ]
[ http://60.8.125.66:8030 | None | 404 | 141 | Sorry - no such page ]
[ http://60.8.125.14:7000 | Apache-Coyote/1.1 | 200 | 7777 | Apache Tomcat ]
[ http://60.8.125.42:9999 | Apache-Coyote/1.1 | 200 | 498 | M1-Server 已启动 ]
[ http://60.8.125.62:9090 | Boa/0.94.13 | 200 | 5437 | WEB configuration ]
[ https://60.8.125.150 | None | 200 | 11004 | DCFW-1800 ]
[ https://60.8.125.226 |  | 200 | 225 | None ]
[ https://60.8.125.66:8443 | HTTP Server 1.0 | 200 | 3633 | None ]
[ https://60.8.125.107:8443 | HTTP Server 1.0 | 200 | 7458 | None ]
[ https://60.8.125.38 | None | 403 | 21 | None ]
[ https://60.8.125.66 | Apache-Coyote/1.1 | 200 | 39242 | None ]
[ http://60.8.125.42:8888 | 【seeyon!!】 | Seeyon-Server/1.0 | 200 | 29709 | 致远A6-V5协同管理软件 V5.6SP1 ]
[ https://60.8.125.108:8443 | HTTP Server 1.0 | 200 | 7458 | None ]
[ https://60.8.125.106:8443 | HTTP Server 1.0 | 200 | 7458 | None ]
[ https://60.8.125.94:60443 | None | 200 | 71708 | None ]
[ http://60.8.125.42:8140 | nginx/1.6.0 | 200 | 4792 | ZKTime9.0 考勤管理系统- 登录 ]
[ https://60.8.125.226/../cgi-bin/login.cgi?ui=web&opr=show&ver=66680_chs |  | 200 | 225 | None ]

重点资产：
[ http://60.8.125.42:8888 | 【seeyon!!】 | Seeyon-Server/1.0 | 200 | 29709 | 致远A6-V5协同管理软件 V5.6SP1 ]


运行时间：9.5518766s
