### ISSUE TITLE
defender报毒

### ISSUE THREAD

**Issue by webs3c** [EdgeSecurityTeam/EHole#9]
3.0版本 Windows defender报毒？？？

**Comment by r0eXpeR** [comment]
有截图方便提供一下吗？

**Comment by webs3c** [comment]
![Snipaste_2021-06-29_09-50-46](https://user-images.githubusercontent.com/6590351/123724876-ad226e00-d8bf-11eb-97c9-b2d2ff1027e1.png)

**Comment by webs3c** [comment]
今天再次扫描了一遍，又没问题了

**Comment by ShiHuang-ESec** [comment]
考虑到go打包太大了，用upx压缩了一下，有时可能会报毒
